services:
 rabbitmq:
  image: rabbitmq:4.0-management
  ports:
   - "5672:5672" #rmq server
   - "15672:15672" #rmq management interface
  environment:
   - RABBITMQ_DEFAULT_USER: raza
   - RABBITMQ_DEFAULT_PASS: raza1315
  volumes:
   - ./rabbitmq_data:/var/lib/rabbitmq